{% set version = "9.6.2" %}

package:
  name: proj
  version: {{ version }}

source:
  url: https://download.osgeo.org/proj/proj-{{ version }}.tar.gz
  sha256: 53d0cafaee3bb2390264a38668ed31d90787de05e71378ad7a8f35bb34c575d1
  patches:
    - 0001-define_OLD_BUGGY_REMQUO.patch
    # Remove after https://github.com/OSGeo/PROJ/pull/4527 is released (9.6.3?)
    - 0002-msvc_c5287_geodesic.patch
    # Remove after https://github.com/OSGeo/PROJ/pull/4526 is released (9.6.3?)
    - 0003-proj_trans_bounds.patch

build:
  number: 2
  run_exports:
    # ABI has been stable across minor versions since 8.0.0
    #    https://abi-laboratory.pro/tracker/timeline/proj/
    - {{ pin_subpackage('proj', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - sqlite  # [build_platform != target_platform]
    - pytest
    - pyyaml
  host:
    - sqlite
    - libtiff
    - libcurl
  run:
    - sqlite
    - libtiff
    - libcurl
  run_constrained:
    - proj4 ==999999999999

test:
  commands:
    - test -f ${PREFIX}/lib/libproj${SHLIB_EXT}  # [unix]
    - test ! -f ${PREFIX}/lib/libproj.a          # [unix]
    - if not exist %LIBRARY_LIB%\\proj.lib exit 1  # [win]
    # See other tests with run_test.py

about:
  home: https://proj.org/
  license: MIT
  license_file: COPYING
  summary: Cartographic Projections and Coordinate Transformations Library

extra:
  recipe-maintainers:
    - hobu
    - msarahan
    - mwtoews
    - ocefpaf
    - pelson
    - snowman2
    - xylar
