{% set version = "9.4.0" %}

package:
  name: proj
  version: {{ version }}

source:
  url: https://download.osgeo.org/proj/proj-{{ version }}.tar.gz
  sha256: 3643b19b1622fe6b2e3113bdb623969f5117984b39f173b4e3fb19a8833bd216
  patches:
    - define_OLD_BUGGY_REMQUO.patch

build:
  number: 1
  run_exports:
    # so name changes in bugfix revisions.  Pin to bugfix revision.
    #    https://abi-laboratory.pro/tracker/timeline/proj/
    - {{ pin_subpackage('proj', max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sqlite     # [build_platform != target_platform]
  host:
    - sqlite
    - libtiff
    - libcurl
  run:
    - sqlite
    - libtiff
    - libcurl
  run_constrained:
    - proj4 ==999999999999

test:
  commands:
    - test -f ${PREFIX}/lib/libproj${SHLIB_EXT}  # [unix]
    - test ! -f ${PREFIX}/lib/libproj.a          # [unix]
    - if not exist %LIBRARY_LIB%\\proj.lib exit 1  # [win]
    # See other tests with run_test.py

about:
  home: https://proj.org/
  license: MIT
  license_file: COPYING
  summary: Cartographic Projections and Coordinate Transformations Library

extra:
  recipe-maintainers:
    - hobu
    - msarahan
    - mwtoews
    - ocefpaf
    - pelson
    - snowman2
    - xylar
