{% set version = "5.0.1" %}

package:
  name: proj4
  version: {{ version }}

source:
  url: http://download.osgeo.org/proj/proj-{{ version }}.tar.gz
  sha256: a792f78897482ed2c4e2af4e8a1a02e294c64e32b591a635c5294cb9d49fdc8c

build:
  number: 0
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - unzip  # [not win]
    - curl  >=7.44.0,<8
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    # Check if NAD27/NAD83 datum shifting is present if `conus` is present.
    - test -f $PREFIX/share/proj/conus  # [not win]
    - if not exist %PREFIX%\\Library\\SHARE\\conus exit 1  # [win]
    - echo -105 40 | proj +proj=utm +zone=13 +ellps=WGS84
    - echo -117 30 | cs2cs +proj=latlong +datum=NAD27 +to +proj=latlong +datum=NAD83
    - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975
    - conda inspect linkages -p $PREFIX proj4  # [not win]
    - conda inspect objects -p $PREFIX proj4  # [osx]

about:
  home: https://proj4.org/
  license: MIT
  license_file: COPYING
  summary: 'Cartographic projection software.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
