{% set version = "9.3.0" %}

package:
  name: proj
  version: {{ version }}

source:
  url: https://download.osgeo.org/proj/proj-{{ version }}.tar.gz
  sha256: 91a3695a004ea28db0448a34460bed4cc3b130e5c7d74339ec999efdab0e547d
  patches:
    - define_OLD_BUGGY_REMQUO.patch

build:
  number: 1
  run_exports:
    # so name changes in bugfix revisions.  Pin to bugfix revision.
    #    https://abi-laboratory.pro/tracker/timeline/proj/
    - {{ pin_subpackage('proj', max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sqlite     # [build_platform != target_platform]
  host:
    - sqlite
    - libtiff
    - libcurl
  run:
    - sqlite
    - libtiff
    - libcurl
  run_constrained:
    - proj4 ==999999999999

test:
  commands:
    - test -f ${PREFIX}/lib/libproj${SHLIB_EXT}  # [unix]
    - test ! -f ${PREFIX}/lib/libproj.a          # [unix]
    - if not exist %LIBRARY_LIB%\\proj.lib exit 1  # [win]
    - echo -105 40 | proj +proj=utm +zone=13 +ellps=WGS84
    - echo -117 30 | cs2cs +proj=latlong +datum=NAD27 +to +proj=latlong +datum=NAD83
    - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975
    - echo -92.199881 38.56694 | proj EPSG:26915 | cs2cs EPSG:26915 +to EPSG:26715

about:
  home: https://proj.org/
  license: MIT
  license_file: COPYING
  summary: Cartographic Projections and Coordinate Transformations Library

extra:
  recipe-maintainers:
    - hobu
    - msarahan
    - mwtoews
    - ocefpaf
    - pelson
    - snowman2
    - xylar
